# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "[47,)"

displayURL = "https://www.curseforge.com/minecraft/mc-mods/spice-of-life-ringo-pie-edition"
logoFile = "logo 160.png"
license = "LGPL-2.1"
credits = "MilesFan, T-Niijima creator of Ringo Pie Edition, Vice, creator of Apple Pie Edition, Kevun1, creator of Spice of Life: Potato Edition, and the Spice of Life: Carrot Edition team, which that project was forked from."
authors = "MilesFan"

[[mods]]
	modId = "solpineapplepie"
	version = "${file.jarVersion}"
	displayName = "Spice of Life: Pineapple Pie Edition"
	description = '''
	A version of Spice of Life Ringo Pie Edition that fixed the bugs in the original mod and added some new QoL features for lunch boxes.
'''

# Dependencies are optional.
[[dependencies]]
	modId = "forge"
	mandatory = true
	versionRange = "[47,)"
	ordering = "NONE" # BEFORE or AFTER required if the relationship is not mandatory
	side = "BOTH" # BOTH, CLIENT or SERVER

[[dependencies]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.20.1,)"
	ordering = "NONE"
	side = "BOTH"
